## Creation of configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: ns-postgres
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgresdb
