## Creation of PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ns-postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres
